### ISSUE TITLE
Apresentação de data negativa

### ISSUE THREAD

**Issue by felipemfp** [chicobentojr/minhaeiro#7]
Por exemplo, ao cadastrar uma movimentação de 3 dias atrás, o aplicativo apresenta: 

> 3 dias atrás

Porém, ao cadastrar uma movimentação que acontecerá daqui a 3 dias, o aplicativo apresenta:

> -3 dias atrás

![bug](https://cloud.githubusercontent.com/assets/8146112/14771173/117f489a-0a59-11e6-83d6-3fc0a2d8c007.jpg)

**Comment by chicobentojr** [comment]
@felipemfp já pode fechar?
